plugins { id "com.android.application" }

android {
    namespace "com.smarttradingai.app"
    compileSdk 35
    defaultConfig {
        applicationId "com.smarttradingai.app"
        minSdk 23
        targetSdk 34
        versionCode 91
        versionName "9.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
