function cookies(header){const o={};String(header||"").split(";").forEach(p=>{const i=p.indexOf("=");if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return o}
const INSTRUMENTS={nifty:"NSE_INDEX|Nifty 50",banknifty:"NSE_INDEX|Nifty Bank",sensex:"BSE_INDEX|SENSEX"};
async function get(url,token){
 const tokens=Array.isArray(token)?token.filter(Boolean):[token];
 let last=null;
 for(const t of tokens){const r=await fetch(url,{headers:{Accept:"application/json",Authorization:"Bearer "+t}});const b=await r.json().catch(()=>({}));if(r.ok)return b;last=new Error(b?.errors?.[0]?.message||b?.message||"Upstox request failed");if(r.status!==401&&r.status!==403)break;}
 throw last||new Error("Upstox request failed");
}
function scoreSide(c,p){let bull=0,bear=0,factors=[];if(c.above_vwap===true){bull++;factors.push("PRICE>VWAP")}if(c.above_vwap===false){bear++;factors.push("PRICE<VWAP")}if(c.structure_5m==="HH-HL"){bull++;factors.push("HH-HL")}if(c.structure_5m==="LH-LL"){bear++;factors.push("LH-LL")}if(c.ema20!=null&&c.ema50!=null){if(c.ema20>c.ema50){bull++;factors.push("EMA20>50")}if(c.ema20<c.ema50){bear++;factors.push("EMA20<50")}}if(c.volume_spike){if(c.candle_bias==="BULLISH"){bull++;factors.push("BULL VOL SPIKE")}if(c.candle_bias==="BEARISH"){bear++;factors.push("BEAR VOL SPIKE")}}if(Number.isFinite(p)){if(p>1.05){bull++;factors.push("PCR>1.05")}if(p<0.95){bear++;factors.push("PCR<0.95")}}return{bull,bear,factors}}
function optionSetup(rows,spot,side){if(!side||!spot||!Array.isArray(rows)||!rows.length)return null;const valid=rows.filter(x=>Number.isFinite(+x.strike_price));if(!valid.length)return null;const atm=valid.reduce((best,x)=>Math.abs(+x.strike_price-spot)<Math.abs(+best.strike_price-spot)?x:best,valid[0]);const opt=side==="CALL"?atm.call_options:atm.put_options;const md=opt?.market_data||{};const premium=Number(md.ltp);if(!Number.isFinite(premium)||premium<=0)return null;const sl=Number((premium*0.80).toFixed(2));const target=Number((premium*1.40).toFixed(2));const lot=Number(opt?.lot_size||opt?.minimum_lot||0);return{strike:Number(atm.strike_price),expiry:atm.expiry||null,option_type:side==="CALL"?"CE":"PE",trading_symbol:opt?.trading_symbol||null,instrument_key:opt?.instrument_key||null,premium:Number(premium.toFixed(2)),stop_loss_premium:sl,target_premium:target,rr:2,lot_size:lot||null,risk_note:"Mechanical premium framework: 20% SL / 40% target; not a prediction."}}
export default async function handler(req,res){res.setHeader("Cache-Control","no-store");if(req.method!=="GET")return res.status(405).json({error:"Method not allowed"});const jar=cookies(req.headers.cookie);const token=[jar.upstox_access_token,jar.upstox_extended_token].filter(Boolean);if(!token.length)return res.status(401).json({connected:false,error:"Upstox not connected"});const key=String(req.query?.underlying||"nifty").toLowerCase();const instrumentKey=INSTRUMENTS[key]||INSTRUMENTS.nifty;
try{
 const c=await get("https://api.upstox.com/v3/historical-candle/intraday/"+encodeURIComponent(instrumentKey)+"/minutes/5",token);
 const candles=(c?.data?.candles||[]).map(x=>({ts:x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5]||0})).reverse();
 if(candles.length<50)return res.status(200).json({connected:true,verdict:"WAIT",reason:"Need at least 50 verified 5-minute candles",confirmation_count:0,required_confirmations:4});
 let pv=0,vv=0;candles.forEach(x=>{const t=(x.high+x.low+x.close)/3;pv+=t*x.volume;vv+=x.volume});const vwap=vv?pv/vv:null;const last=candles.at(-1); const latestMs=Date.parse(last.ts); const ageMin=Number.isFinite(latestMs)?(Date.now()-latestMs)/60000:Infinity; const istNow=new Date(new Date().toLocaleString("en-US",{timeZone:"Asia/Kolkata"})); const mins=istNow.getHours()*60+istNow.getMinutes(); const marketSession=mins>=555&&mins<=930; const dataFresh=!marketSession||ageMin<=15;
 const closes=candles.map(x=>x.close);function ema(a,n){const k=2/(n+1);let e=a.slice(0,n).reduce((s,v)=>s+v,0)/n;for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
 const ema20=ema(closes,20),ema50=ema(closes,50),recent=candles.slice(-8),mid=4,h1=Math.max(...recent.slice(0,mid).map(x=>x.high)),h2=Math.max(...recent.slice(mid).map(x=>x.high)),l1=Math.min(...recent.slice(0,mid).map(x=>x.low)),l2=Math.min(...recent.slice(mid).map(x=>x.low)),structure=h2>h1&&l2>l1?"HH-HL":h2<h1&&l2<l1?"LH-LL":"MIXED",avg=candles.slice(-11,-1).reduce((s,x)=>s+x.volume,0)/10,vr=avg?last.volume/avg:null,volumeSpike=vr!=null&&vr>=1.5;
 let pcr=null,rows=[],expiry=null,chainNote="Option-chain confirmation unavailable";
 try{const oc=await get("https://api.upstox.com/v2/option/chain?instrument_key="+encodeURIComponent(instrumentKey)+"&expiry_date=current_week",token);rows=Array.isArray(oc?.data)?oc.data:[];const co=rows.reduce((s,x)=>s+(+x?.call_options?.market_data?.oi||0),0),po=rows.reduce((s,x)=>s+(+x?.put_options?.market_data?.oi||0),0);if(co)pcr=po/co;expiry=rows[0]?.expiry||null;chainNote=rows.length?"PCR + option prices from verified Upstox option-chain response":"Option-chain returned no rows"}catch(e){chainNote="Option-chain confirmation unavailable: "+e.message}
 const aboveVWAP=vwap!=null?last.close>vwap:null;let marketRegime="TRANSITION",allowedSetup=["WAIT FOR CONFIRMATION"];if(structure==="HH-HL"&&ema20>ema50&&aboveVWAP===true){marketRegime="TREND UP";allowedSetup=["VWAP/PULLBACK CALL","BREAKOUT + VOLUME CALL"]}else if(structure==="LH-LL"&&ema20<ema50&&aboveVWAP===false){marketRegime="TREND DOWN";allowedSetup=["VWAP/PULLBACK PUT","BREAKDOWN + VOLUME PUT"]}else if(structure==="MIXED"&&Math.abs(ema20-ema50)/Math.max(1,last.close)<0.002){marketRegime="RANGE";allowedSetup=["RANGE EXTREMES ONLY","NO MID-RANGE CHASE"]}else if((structure==="HH-HL"&&ema20<ema50)||(structure==="LH-LL"&&ema20>ema50)){marketRegime="REVERSAL WATCH";allowedSetup=["WAIT FOR CHoCH/BOS","VWAP RECLAIM/REJECTION"]}else if(aboveVWAP===true&&ema20>=ema50){marketRegime="EARLY TREND UP";allowedSetup=["VWAP HOLD + VOLUME"]}else if(aboveVWAP===false&&ema20<=ema50){marketRegime="EARLY TREND DOWN";allowedSetup=["VWAP REJECTION + VOLUME"]}const cctx={above_vwap:aboveVWAP,structure_5m:structure,ema20,ema50,volume_spike:volumeSpike,candle_bias:last.close>last.open?"BULLISH":last.close<last.open?"BEARISH":"NEUTRAL"};const s=scoreSide(cctx,pcr),max=Math.max(s.bull,s.bear),same=s.bull===s.bear;const regimeBlocks=(marketRegime==="RANGE"||marketRegime==="REVERSAL WATCH"||marketRegime==="TRANSITION");const directionMismatch=(marketRegime==="TREND UP"&&s.bear>s.bull)||(marketRegime==="TREND DOWN"&&s.bull>s.bear);const verdict=!Number.isFinite(pcr)||same||max<4||regimeBlocks||directionMismatch?"WAIT":s.bull>s.bear?"CALL":"PUT";
 const spot=rows[0]?.underlying_spot_price||last.close;
 const option=verdict==="WAIT"?null:optionSetup(rows,spot,verdict);
 const atmRow=rows.find(x=>Number(x.strike_price)===Number(option?.strike))||null;
 const atmCE=atmRow?.call_options?.market_data||{}, atmPE=atmRow?.put_options?.market_data||{};
 const atmOiCE=Number(atmCE.oi||0), atmOiPE=Number(atmPE.oi||0), atmVolCE=Number(atmCE.volume||0), atmVolPE=Number(atmPE.volume||0);
 const atmOiChangeCE=Number(atmCE.oi_change||atmCE.change_in_oi||0), atmOiChangePE=Number(atmPE.oi_change||atmPE.change_in_oi||0);
 let optionQuality=option?50:0; const optionQualityReasons=[];
 if(option){ if(Number.isFinite(pcr)&&((verdict==="CALL"&&pcr>=1)||(verdict==="PUT"&&pcr<=1))){optionQuality+=15;optionQualityReasons.push("PCR supports direction")} else optionQualityReasons.push("PCR not strongly aligned");
   const volOk=verdict==="CALL"?atmVolCE>=atmVolPE:atmVolPE>=atmVolCE; if(volOk){optionQuality+=10;optionQualityReasons.push("ATM volume supports direction")} else optionQuality-=5;
   const oiOk=verdict==="CALL"?atmOiChangePE>=atmOiChangeCE:atmOiChangeCE>=atmOiChangePE; if(oiOk){optionQuality+=10;optionQualityReasons.push("OI shift supports direction")} else optionQuality-=5;
   if(volumeSpike){optionQuality+=10;optionQualityReasons.push("underlying volume spike")} if(aboveVWAP===(verdict==="CALL")){optionQuality+=5;optionQualityReasons.push("VWAP alignment")}
 }
 optionQuality=Math.max(0,Math.min(100,Math.round(optionQuality)));
 const optionGrade=optionQuality>=85?"A+":optionQuality>=75?"A":optionQuality>=65?"B":optionQuality>=55?"C":"D";
 const entryReady=verdict!=="WAIT"&&Number.isFinite(spot)&&Number.isFinite(vwap)&&Number.isFinite(vr)&&vr>0&&Number.isFinite(pcr)&&dataFresh;
 const riskReady=option&&Number.isFinite(option.premium)&&option.premium>0&&Number.isFinite(option.stop_loss_premium)&&Number.isFinite(option.target_premium)&&option.rr>=2&&Number(option.lot_size)>0;
 const confirmationReady=max>=4&&!same&&!regimeBlocks&&!directionMismatch&&Number.isFinite(pcr);
 const finalGate=entryReady&&riskReady&&confirmationReady?"OPEN":"WAIT";
 const finalVerdict=finalGate==="OPEN"?verdict:"WAIT";
 const gateReasons=[];
 if(!confirmationReady)gateReasons.push("confirmation gate failed");
 if(!entryReady)gateReasons.push(dataFresh?"entry/data gate failed":"market data stale");
 if(!riskReady)gateReasons.push("risk/R:R gate failed");
 const reason=finalGate==="WAIT"?(gateReasons.length?gateReasons.join(" • "):"Final trade gate is WAIT"):"All gates passed: regime + confirmation + entry + risk/R:R";
 return res.status(200).json({connected:true,underlying:key,verdict:finalVerdict,confidence:max,confidence_pct:confidencePct,confidence_label:confidencePct>=80?"HIGH":confidencePct>=60?"MEDIUM":"LOW",confirmation_count:max,required_confirmations:4,reason,market_regime:marketRegime,allowed_setup:allowedSetup,regime_trade_gate:regimeBlocks?"WAIT":"OPEN",data_quality:{fresh:dataFresh,age_minutes:Number.isFinite(ageMin)?Number(Math.max(0,ageMin).toFixed(1)):null,market_session:marketSession},trade_gate:{regime:regimeBlocks?"WAIT":"OPEN",direction:directionMismatch?"WAIT":"PASS",confirmations:confirmationReady?"PASS":"WAIT",entry:entryReady?"PASS":"WAIT",risk_rr:riskReady?"PASS":"WAIT",final:finalGate,reasons:gateReasons},factors:s.factors,pcr:Number.isFinite(pcr)?Number(pcr.toFixed(3)):null,vwap:vwap?Number(vwap.toFixed(2)):null,structure,volume_ratio:vr?Number(vr.toFixed(2)):null,option_quality:option?{score:optionQuality,grade:optionGrade,reasons:optionQualityReasons,atm_oi:{ce:atmOiCE,pe:atmOiPE,ce_change:atmOiChangeCE,pe_change:atmOiChangePE},atm_volume:{ce:atmVolCE,pe:atmVolPE}}:null,option_setup:finalGate==="OPEN"?option:null,expiry:expiry||option?.expiry||null,chain_note:chainNote});
}catch(e){return res.status(502).json({connected:true,verdict:"WAIT",error:"Decision engine unavailable",message:e.message})}}
